### PR TITLE
Update piwik for 15.0

### PR DESCRIPTION
**Pull request by OnGle**

### CODE REVIEW

**Comment by JedMeister** [comment]
Looks good, but needs changelog.

**Comment by OnGle** [comment]
Don't merge yet, still needs changelog

**Comment by OnGle** [comment]
Should be good. Biggest change is name migration from piwik to matomo. @JedMeister will need to rename the repo as well.

**Comment by JedMeister** [comment]
Great work on this, thanks for that. 

What I'm thinking though, is that we should wait until I hear back from Piwik/Matomo dev on if/when the debian repo will be updated. 

If it won't be, we may need to switch to a tarball install (well actually, it'd be a 'zipball' install, but semantics aside...). 

As I mentioned recently offline, whilst that will be a little bit of a pain to switch to a tarball install, hopefully it shouldn't be too bad as we already do a curl install (the Debian package appears to just place the files, the final web UI install is still required and is currently done via curl in the `conf.d/main`).

**Comment by OnGle** [comment]
Oops, didn't realise there was still a PR open and force-pushed to this branch. FWIW, This branch does now contain 15.0-update changes using the new matomo debian repo. Would it be cleaner to open a new pull request though because the 2 branches have different bases?

**Comment by OnGle** [comment]
Thanks for the heads up, looks like I made those changes in a separate branch and never pushed. Regardless here they are now :)

**Pull request merged**
